<?php

namespace AppBundle\Entity\Repository;

/**
 * CurrencyInventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyInventoryRepository extends \Doctrine\ORM\EntityRepository
{
}
